### ISSUE TITLE
Mac terminal port

### ISSUE THREAD

**Issue by paullinnerud** [microsoft/VisualTrueType#3]
Once Windows dependency is removed, add a Mac XCode terminal project.

**Comment by simoncozens** [comment]
Rather than OS specific builds, it would be better to move to a cross-platform build system. Apparently there’s a tool which can convert MSVS project files to CMakeLists and we can maybe build with ninja. I’ll give that a try on Monday.

**Comment by HinTak** [comment]
@simoncozens I already finished the port - see https://github.com/microsoft/VisualTrueType/issues/9 (and https://github.com/microsoft/VisualTrueType/issues/8) . It is just GNU Make for linux, mac, and also cross-compiling for 32-bit/64-bit windows. no need for anything beyond GNU Make.

**Comment by simoncozens** [comment]
What you've done with the port is great, but now we have two build systems (Windows and everything else) instead of one cross-platform one.

**Comment by twardoch** [comment]
But these are »low-hanging fruit« build systems. GNU make is commonplace on Linux and Mac, while VS is common on Windows. :)

**Comment by HinTak** [comment]
Yes, the last time I checked, GNU make is part of Xcode, or the commandline tool set of Xcode. Cmake is not .

**Comment by HinTak** [comment]
There is one file with a lot of non-ascii and non-utf8 string literals in. In @schriftgestalt 's port, he changed them to hex or something; I assume them to be in cp1251 (windows encoding) and I use the gcc command line switch "-finput-charset=cp1251" to cope. There is another file with a not-quite c++ construct (mentioned in the make file) which needs -fpermissive . I haven't looked at how @schriftgestalt with it. Those are the two things to correct in the c++ code to make it work for any standard-compliant c++ compiler (I am talking about clang...).

**Comment by HinTak** [comment]
I read up the Microsoft documentation about the non-ascii/non-utf8 wide string literals. According to microsoft documentation, they are Microsoft specific and treated by the Microsoft compiler as raw 8-bit values. @schriftgestalt converted them to hex value, is one way of doing it (he didn't write in a comment etc why, so I did not copy his change; instead I just made a guess of what encoding Microsoft compiler wants it as, and make gcc do the same - and that turns out to be correct too). Using the gcc specific "-finput-charset=cp1251" is simpler and also correct too, as raw 8-bit is what cp1251 is; but it is gcc-specific. So clang and other compiler users will want the hex values.

**Comment by schriftgestalt** [comment]
> he didn't write in a comment etc why, so I did not copy his change
Xcode complained about them so I tried to get rid of it. 

And I still would prefer to have an Xcode project as I’m more familiar with it and it makes debugging and the code signing much easier. I’ll can make one later.

Are there test cases? What would be a platform independent way of doing them?

**Comment by HinTak** [comment]
Yeah, non-microsoft compilers treat non-ascii fragments as utf8 in general, so not surprised xcode does not like those. The makefile is just the smallest thing to make my life easy (it is only 10/15 lines). I don't object to using multiple build systems. In fact, I can just merge @schriftgestalt 's xcode project in, and adjust for the mixed-case/case-sensitivity pull already merged. Strictly speaking, it has no effect on native mac builds on macs, since mac file systems are case-preserving but not case-sensitive. But it is nicer to refer to files by their proper mixed-case names everywhere.

I'll have a look at what @schriftgestalt did to cope with the issue I did with -fpermissive (this I think is common to gcc and clang so less important, as far as using non-Microsoft compilers go). Then we have essentially scrub up the code to work with all the major in-use c++ compilers...

**Comment by schriftgestalt** [comment]
I didn't deal with it. I don't use c++. 
Xcode should be able to use the same command line arguments in the build settings.

**Comment by HinTak** [comment]
> I didn't deal with it. I don't use c++. Xcode should be able to use the same command line arguments in the build settings.

:) . I looked properly and found where I used -fpermissive to get gcc to go foreward, you have simply commented out the offending lines :). Anyway, I have merged/cherry-picked your xcode proj stuff onto my repo, @schriftgestalt , so would appreciate if you give it a try and see if I made a mistake in the merge/cherry-pick.

**Comment by HinTak** [comment]
I have made it built with clang too, so should build natively with on xcode also.

**Comment by schriftgestalt** [comment]
Why I like to work in Xcode is because is gives very good feedback:
```
vttcompile Group
Parse Issue Group
	getopt.h:23:4: Add explicit braces to avoid dangling else
	vttcompile.cpp:14:10: In file included from 	vttcompile.cpp:14:
	TTGenerator.cpp:2508:8: Add explicit braces to avoid dangling else
	TTGenerator.cpp:2522:8: Add explicit braces to avoid dangling else
	TTFont.cpp:5417:8: Add explicit braces to avoid dangling else
Unused Entity Issue Group
	Variation.cpp:120:23: Unused variable 'peak'
	TTGenerator.cpp:2218:8: Unused variable 'deltaAngle'
	TTEngine.cpp:1084:2: Expression result unused
	TTAssembler.cpp:3577:18: Unused variable 'argTypeBuffer'
	TMTParser.cpp:1014:111: Unused variable 'parent1Param'
	TMTParser.cpp:1093:11: Unused variable 'cvt0ParamOffs'
	TMTParser.cpp:1094:8: Unused variable 'cvt1ParamOffs'
	TMTParser.cpp:1131:11: Unused variable 'cvt0ParamOffs'
	TMTParser.cpp:1132:8: Unused variable 'cvt1ParamOffs'
	TMTParser.cpp:1174:7: Unused variable 'haveMinDist'
	TMTParser.cpp:1199:11: Unused variable 'optParamOffs'
	TMTParser.cpp:1205:7: Unused variable 'haveMinDist'
	TTFont.cpp:1118:12: Unused variable 'pdefaultValue'
	TTFont.cpp:1123:12: Unused variable 'pmaxValue'
	TTFont.cpp:2251:7: Unused variable 'axisCount'
	TTFont.cpp:2407:7: Unused variable 'tupleCount'
Semantic Issue Group
	TTGenerator.cpp:393:47: '&&' within '||'
	TTGenerator.cpp:393:47: Place parentheses around the '&&' expression to silence this warning
	TTGenerator.cpp:511:34: '&&' within '||'
	TTGenerator.cpp:511:34: Place parentheses around the '&&' expression to silence this warning
	TTGenerator.cpp:511:91: '&&' within '||'
	TTGenerator.cpp:511:91: Place parentheses around the '&&' expression to silence this warning
	TTGenerator.cpp:516:42: '&&' within '||'
	TTGenerator.cpp:516:42: Place parentheses around the '&&' expression to silence this warning
	TTGenerator.cpp:516:99: '&&' within '||'
	TTGenerator.cpp:516:99: Place parentheses around the '&&' expression to silence this warning
	TTGenerator.cpp:546:80: '&&' within '||'
	TTGenerator.cpp:546:80: Place parentheses around the '&&' expression to silence this warning
	TTGenerator.cpp:576:41: '&&' within '||'
	TTGenerator.cpp:576:41: Place parentheses around the '&&' expression to silence this warning
	TTGenerator.cpp:576:95: '&&' within '||'
	TTGenerator.cpp:576:95: Place parentheses around the '&&' expression to silence this warning
	TTGenerator.cpp:597:46: Variable 'deltaR' may be uninitialized when used here
	TTGenerator.cpp:486:2: Variable 'deltaR' is declared here
	TTGenerator.cpp:546:52: Variable 'distance' may be uninitialized when used here
	TTGenerator.cpp:484:16: Initialize the variable 'distance' to silence this warning
	TTGenerator.cpp:737:44: '&&' within '||'
	TTGenerator.cpp:737:44: Place parentheses around the '&&' expression to silence this warning
	TTGenerator.cpp:871:11: Enumeration value 'fvInherit' not handled in switch
	TTGenerator.cpp:871:11: Add missing switch cases
	TTGenerator.cpp:1307:69: '&&' within '||'
	TTGenerator.cpp:1307:69: Place parentheses around the '&&' expression to silence this warning
	TTGenerator.cpp:1307:150: '&&' within '||'
	TTGenerator.cpp:1307:150: Place parentheses around the '&&' expression to silence this warning
	TTGenerator.cpp:1327:69: '&&' within '||'
	TTGenerator.cpp:1327:69: Place parentheses around the '&&' expression to silence this warning
	TTGenerator.cpp:1327:150: '&&' within '||'
	TTGenerator.cpp:1327:150: Place parentheses around the '&&' expression to silence this warning
	TTGenerator.cpp:1841:28: Variable 'y' may be uninitialized when used here
	TTGenerator.cpp:1827:11: Initialize the variable 'y' to silence this warning
	TTGenerator.cpp:2251:34: Variable 'diagChild' may be uninitialized when used here
	TTGenerator.cpp:2219:17: Initialize the variable 'diagChild' to silence this warning
	TTGenerator.cpp:2317:34: Variable 'diagChild' may be uninitialized when used here
	TTGenerator.cpp:2287:17: Initialize the variable 'diagChild' to silence this warning
	TTGenerator.cpp:2422:19: '&&' within '||'
	TTGenerator.cpp:2422:19: Place parentheses around the '&&' expression to silence this warning
	TTGenerator.cpp:2528:19: '&&' within '||'
	TTGenerator.cpp:2528:19: Place parentheses around the '&&' expression to silence this warning
	TTGenerator.cpp:2552:29: Variable 'labels' may be uninitialized when used here
	pch.h:55:48: Expanded from macro 'swprintf'
	TTGenerator.cpp:2392:31: Initialize the variable 'labels' to silence this warning
	TTEngine.cpp:419:29: '&&' within '||'
	TTEngine.cpp:419:29: Place parentheses around the '&&' expression to silence this warning
	TTEngine.cpp:419:71: '&&' within '||'
	TTEngine.cpp:419:71: Place parentheses around the '&&' expression to silence this warning
	TTEngine.cpp:422:44: '&&' within '||'
	TTEngine.cpp:422:44: Place parentheses around the '&&' expression to silence this warning
	TTEngine.cpp:422:92: '&&' within '||'
	TTEngine.cpp:422:92: Place parentheses around the '&&' expression to silence this warning
	TTEngine.cpp:868:60: Shifting a negative signed value is undefined
	TTAssembler.cpp:2864:41: Variable 'InstructionCode' may be uninitialized when used here
	TTAssembler.cpp:2847:35: Initialize the variable 'InstructionCode' to silence this warning
	TTAssembler.cpp:2657:15: Variable 'SwitchCode' may be uninitialized when used here
	TTAssembler.cpp:2638:31: Initialize the variable 'SwitchCode' to silence this warning
	TTAssembler.cpp:3788:120: Variable 'RoundingCode' may be uninitialized when used here
	TTAssembler.cpp:3737:44: Initialize the variable 'RoundingCode' to silence this warning
	TTAssembler.cpp:3805:132: Variable 'currInstrIndex' may be uninitialized when used here
	TTAssembler.cpp:3737:59: Initialize the variable 'currInstrIndex' to silence this warning
	TTAssembler.cpp:3788:156: Variable 'argc' may be uninitialized when used here
	TTAssembler.cpp:3737:89: Initialize the variable 'argc' to silence this warning
	TTAssembler.cpp:3788:134: Variable 'prevInstrIndex' may be uninitialized when used here
	TTAssembler.cpp:3737:74: Initialize the variable 'prevInstrIndex' to silence this warning
	TTAssembler.cpp:3966:18: '&' within '|'
	TTAssembler.cpp:3966:18: Place parentheses around the '&' expression to silence this warning
	TTAssembler.cpp:3973:18: '&' within '|'
	TTAssembler.cpp:3973:18: Place parentheses around the '&' expression to silence this warning
	TTAssembler.cpp:3991:14: Variable 'xscale' may be uninitialized when used here
	pch.h:55:48: Expanded from macro 'swprintf'
	TTAssembler.cpp:3927:43: Initialize the variable 'xscale' to silence this warning
	TTAssembler.cpp:3991:50: Variable 'scale01' may be uninitialized when used here
	pch.h:55:48: Expanded from macro 'swprintf'
	TTAssembler.cpp:3927:58: Initialize the variable 'scale01' to silence this warning
	TTAssembler.cpp:3992:14: Variable 'scale10' may be uninitialized when used here
	pch.h:55:48: Expanded from macro 'swprintf'
	TTAssembler.cpp:3927:66: Initialize the variable 'scale10' to silence this warning
	TTAssembler.cpp:3992:50: Variable 'yscale' may be uninitialized when used here
	pch.h:55:48: Expanded from macro 'swprintf'
	TTAssembler.cpp:3927:50: Initialize the variable 'yscale' to silence this warning
	TMTParser.cpp:372:18: Variable 'params' may be uninitialized when used here
	TMTParser.cpp:363:14: Initialize the variable 'params' to silence this warning
	TMTParser.cpp:535:84: '&&' within '||'
	TMTParser.cpp:535:84: Place parentheses around the '&&' expression to silence this warning
	TMTParser.cpp:535:128: '&&' within '||'
	TMTParser.cpp:535:128: Place parentheses around the '&&' expression to silence this warning
	TMTParser.cpp:922:12: 126 enumeration values not handled in switch: 'align', 'asM', 'autoHinter'...
	TMTParser.cpp:922:12: Add missing switch cases
	TMTParser.cpp:934:169: Variable 'r' may be uninitialized when used here
	TMTParser.cpp:919:4: Variable 'r' is declared here
	TMTParser.cpp:1294:37: '&&' within '||'
	TMTParser.cpp:1294:37: Place parentheses around the '&&' expression to silence this warning
	TMTParser.cpp:1321:38: '&&' within '||'
	TMTParser.cpp:1321:38: Place parentheses around the '&&' expression to silence this warning
	TMTParser.cpp:1265:26: Variable 'parmPos' may be uninitialized when used here
	TMTParser.cpp:1244:30: Initialize the variable 'parmPos' to silence this warning
	TMTParser.cpp:1358:10: 128 enumeration values not handled in switch: 'align', 'asM', 'autoHinter'...
	TMTParser.cpp:1358:10: Add missing switch cases
	TMTParser.cpp:1543:46: Variable 'ttvSym' may be uninitialized when used here
	TMTParser.cpp:1443:2: Variable 'ttvSym' is declared here
	TMTParser.cpp:1535:25: Variable 'firstLocalParamStart' may be uninitialized when used here
	TMTParser.cpp:1445:36: Initialize the variable 'firstLocalParamStart' to silence this warning
	TMTParser.cpp:1572:50: '&&' within '||'
	TMTParser.cpp:1572:50: Place parentheses around the '&&' expression to silence this warning
	TMTParser.cpp:1574:97: '&&' within '||'
	TMTParser.cpp:1574:97: Place parentheses around the '&&' expression to silence this warning
	TMTParser.cpp:1575:33: '&&' within '||'
	TMTParser.cpp:1575:33: Place parentheses around the '&&' expression to silence this warning
	TMTParser.cpp:1576:63: '&&' within '||'
	TMTParser.cpp:1576:63: Place parentheses around the '&&' expression to silence this warning
	TMTParser.cpp:1577:36: '&&' within '||'
	TMTParser.cpp:1577:36: Place parentheses around the '&&' expression to silence this warning
	TMTParser.cpp:1695:39: '&&' within '||'
	TMTParser.cpp:1695:39: Place parentheses around the '&&' expression to silence this warning
	TMTParser.cpp:1923:47: '&&' within '||'
	TMTParser.cpp:1923:47: Place parentheses around the '&&' expression to silence this warning
	TMTParser.cpp:1980:7: Variable 'diff' may be uninitialized when used here
	TMTParser.cpp:1973:16: Initialize the variable 'diff' to silence this warning
	CvtManager.cpp:591:48: '&&' within '||'
	CvtManager.cpp:591:48: Place parentheses around the '&&' expression to silence this warning
	CvtManager.cpp:780:72: '&' within '|'
	CvtManager.cpp:780:72: Place parentheses around the '&' expression to silence this warning
	CvtManager.cpp:764:10: 32 enumeration values not handled in switch: 'group', 'color', 'direction'...
	CvtManager.cpp:764:10: Add missing switch cases
	CvtManager.cpp:831:11: 34 enumeration values not handled in switch: 'group', 'color', 'direction'...
	CvtManager.cpp:831:11: Add missing switch cases
	CvtManager.cpp:874:2: Variable 'cvt' may be uninitialized when used here
	CvtManager.cpp:868:19: Initialize the variable 'cvt' to silence this warning
	CvtManager.cpp:892:11: 33 enumeration values not handled in switch: 'fpgmBias', 'instructionsOn', 'dropOutCtrlOff'...
	CvtManager.cpp:892:11: Add missing switch cases
	CvtManager.cpp:956:7: Logical not is only applied to the left hand side of this bitwise operator
	CvtManager.cpp:956:7: Add parentheses after the '!' to evaluate the bitwise operator first
	CvtManager.cpp:956:7: Add parentheses around left hand side expression to silence this warning
	CvtManager.cpp:1042:35: '&&' within '||'
	CvtManager.cpp:1042:35: Place parentheses around the '&&' expression to silence this warning
	CvtManager.cpp:1042:102: '&&' within '||'
	CvtManager.cpp:1042:102: Place parentheses around the '&&' expression to silence this warning
	CvtManager.cpp:1064:10: 33 enumeration values not handled in switch: 'group', 'color', 'direction'...
	CvtManager.cpp:1064:10: Add missing switch cases
	CvtManager.cpp:1068:27: Shifting a negative signed value is undefined
	CvtManager.cpp:1225:57: Variable 'memError' may be uninitialized when used here
	CvtManager.cpp:1213:15: Initialize the variable 'memError' to silence this warning
	CvtManager.cpp:1467:18: Result of comparison of constant -1 with expression of type 'CvtCategory' is always false
	TTFont.cpp:404:40: '&&' within '||'
	TTFont.cpp:404:40: Place parentheses around the '&&' expression to silence this warning
	TTFont.cpp:405:14: '&&' within '||'
	TTFont.cpp:405:14: Place parentheses around the '&&' expression to silence this warning
	TTFont.cpp:754:34: '&&' within '||'
	TTFont.cpp:754:34: Place parentheses around the '&&' expression to silence this warning
	TTFont.cpp:755:92: '&&' within '||'
	TTFont.cpp:755:92: Place parentheses around the '&&' expression to silence this warning
	TTFont.cpp:3804:20: Variable 'sfntPos' may be uninitialized when used here
	TTFont.cpp:3301:23: Initialize the variable 'sfntPos' to silence this warning
	TTFont.cpp:3533:16: Variable 'numberOfHMetrics' may be uninitialized when used here
	TTFont.cpp:3300:57: Initialize the variable 'numberOfHMetrics' to silence this warning
	TTFont.cpp:4296:20: Variable 'sfntPos' may be uninitialized when used here
	TTFont.cpp:3944:23: Initialize the variable 'sfntPos' to silence this warning
	TTFont.cpp:4307:21: Variable 'numberOfGlyphs' may be uninitialized when used here
	TTFont.cpp:3943:48: Initialize the variable 'numberOfGlyphs' to silence this warning
	TTFont.cpp:4103:16: Variable 'numberOfHMetrics' may be uninitialized when used here
	TTFont.cpp:3943:66: Initialize the variable 'numberOfHMetrics' to silence this warning
	TTFont.cpp:5320:189: '&&' within '||'
	TTFont.cpp:5320:189: Place parentheses around the '&&' expression to silence this warning
	TTFont.cpp:5450:189: '&&' within '||'
	TTFont.cpp:5450:189: Place parentheses around the '&&' expression to silence this warning
	TTFont.cpp:5601:54: Variable 'whoseMetrics' may be uninitialized when used here
	TTFont.cpp:5434:55: Initialize the variable 'whoseMetrics' to silence this warning
Lexical or Preprocessor Issue Group
	Memory.cpp:9:10: Non-portable path to file '"Memory.h"'; specified path differs in case from file name on disk
Value Conversion Issue Group
	File.cpp:64:34: Implicit conversion loses integer precision: 'long' to 'int'
	TTFont.cpp:1114:22: Implicit conversion loses integer precision: 'int32' (aka 'long') to 'int32_t' (aka 'int')
	opentypedefs.h:80:22: Expanded from macro 'SWAPL'
	TTFont.cpp:1119:26: Implicit conversion loses integer precision: 'int32' (aka 'long') to 'int32_t' (aka 'int')
	opentypedefs.h:80:22: Expanded from macro 'SWAPL'
	TTFont.cpp:1124:22: Implicit conversion loses integer precision: 'int32' (aka 'long') to 'int32_t' (aka 'int')
	opentypedefs.h:80:22: Expanded from macro 'SWAPL'
	TTFont.cpp:1147:21: Implicit conversion loses integer precision: 'int32' (aka 'long') to 'int32_t' (aka 'int')
	opentypedefs.h:80:22: Expanded from macro 'SWAPL'
	TTFont.cpp:2187:22: Implicit conversion loses integer precision: 'int32' (aka 'long') to 'uint32_t' (aka 'unsigned int')
	opentypedefs.h:80:22: Expanded from macro 'SWAPL'
Dead store Group
	VariationModels.cpp:253:5: Value stored to 'haveBox' is never read
	TTEngine.cpp:884:3: Value stored to 'offsFn' is never read
	TTEngine.cpp:1095:2: Value stored to 'pos' is never read
	vttcompile.cpp:268:2: Value stored to 'done' is never read
	vttcompile.cpp:429:2: Value stored to 'fromGlyph' is never read
	vttcompile.cpp:429:32: Value stored to 'fromChar' is never read
	vttcompile.cpp:500:12: Value stored to 'done' is never read
	vttcompile.cpp:634:3: Value stored to 'haveRange' is never read
	TTGenerator.cpp:1834:39: Value stored to 'dist' is never read
	TTGenerator.cpp:1835:42: Value stored to 'dist' is never read
	TTGenerator.cpp:2218:8: Value stored to 'deltaAngle' during its initialization is never read
	TTAssembler.cpp:1291:2: Value stored to 'valid' is never read
	TTAssembler.cpp:1546:3: Value stored to 'tempP' is never read
	TTAssembler.cpp:1652:2: Value stored to 'argindex' is never read
	TTAssembler.cpp:2567:2: Value stored to 'ghtblock' is never read
	TTAssembler.cpp:3577:18: Value stored to 'argTypeBuffer' during its initialization is never read
	TTAssembler.cpp:3579:2: Value stored to 'argindex' is never read
	TTAssembler.cpp:3608:4: Value stored to 'tempP' is never read
	TMTParser.cpp:1014:111: Value stored to 'parent1Param' during its initialization is never read
	TMTParser.cpp:1093:11: Value stored to 'cvt0ParamOffs' during its initialization is never read
	TMTParser.cpp:1094:8: Value stored to 'cvt1ParamOffs' during its initialization is never read
	TMTParser.cpp:1131:11: Value stored to 'cvt0ParamOffs' during its initialization is never read
	TMTParser.cpp:1132:8: Value stored to 'cvt1ParamOffs' during its initialization is never read
	TMTParser.cpp:1174:7: Value stored to 'haveMinDist' during its initialization is never read
	TMTParser.cpp:1199:11: Value stored to 'optParamOffs' during its initialization is never read
	TMTParser.cpp:1205:7: Value stored to 'haveMinDist' during its initialization is never read
	TMTParser.cpp:1344:4: Value stored to 'parmPos' is never read
	TMTParser.cpp:2004:93: Value stored to 'replLen' is never read
	TMTParser.cpp:2005:93: Value stored to 'replLen' is never read
	Area.cpp:116:4: Value stored to 'right' is never read
	File.cpp:79:3: Value stored to 'size' is never read
	File.cpp:159:3: Value stored to 'size' is never read
	CvtManager.cpp:1658:2: Value stored to 'newFormat' is never read
	CvtManager.cpp:1665:5: Value stored to 'pos' is never read
	TTFont.cpp:765:3: Value stored to 'knot' is never read
	TTFont.cpp:825:4: Value stored to 'n' is never read
	TTFont.cpp:1118:12: Value stored to 'pdefaultValue' during its initialization is never read
	TTFont.cpp:1123:12: Value stored to 'pmaxValue' during its initialization is never read
	TTFont.cpp:1412:3: Value stored to 'weHaveInstructions' is never read
	TTFont.cpp:1508:4: Value stored to 'sp' is never read
	TTFont.cpp:2251:7: Value stored to 'axisCount' during its initialization is never read
	TTFont.cpp:2407:7: Value stored to 'tupleCount' during its initialization is never read
	TTFont.cpp:3042:2: Value stored to 'glyphIdArray' is never read
	TTFont.cpp:3665:5: Value stored to 'sizeOfTable' is never read
	TTFont.cpp:3705:7: Value stored to 'sizeOfTable' is never read
	TTFont.cpp:5377:48: Value stored to 'delta' is never read
	TTFont.cpp:5387:48: Value stored to 'delta' is never read
	TTFont.cpp:5438:2: Value stored to 'size' is never read
	TTFont.cpp:5461:2: Value stored to 'composite' is never read
	TTFont.cpp:5466:3: Value stored to 'composite' is never read
Logic error Group
	TTEngine.cpp:868:60: The result of the left shift is undefined because the left operand is negative
	vttcompile.cpp:242:7: Called C++ object pointer is null
	vttcompile.cpp:465:17: Called C++ object pointer is null
	vttcompile.cpp:472:7: Called C++ object pointer is null
	TTGenerator.cpp:918:5: 2nd function call argument is an uninitialized value
	TTGenerator.cpp:1315:5: 2nd function call argument is an uninitialized value
	TMTParser.cpp:372:16: The right operand of '<' is a garbage value
	TMTParser.cpp:1265:3: 1st function call argument is an uninitialized value
	TMTParser.cpp:1319:15: Assigned value is garbage or undefined
	TMTParser.cpp:1543:53: The left operand of '==' is a garbage value
	TMTParser.cpp:1543:97: The left operand of '==' is a garbage value
	TMTParser.cpp:1744:38: Assigned value is garbage or undefined
	TMTParser.cpp:1767:16: The left operand of '<' is a garbage value
	TMTParser.cpp:1767:48: The left operand of '<' is a garbage value
	TMTParser.cpp:1773:27: The left operand of '!=' is a garbage value
	TMTParser.cpp:1773:43: The left operand of '<' is a garbage value
	TMTParser.cpp:1979:54: The right operand of '<=' is a garbage value
	TMTParser.cpp:1980:12: The left operand of '>' is a garbage value
	TMTParser.cpp:2002:57: The left operand of '==' is a garbage value
	CvtManager.cpp:580:25: The left operand of '-' is a garbage value
	CvtManager.cpp:1068:27: The result of the left shift is undefined because the left operand is negative
	TTFont.cpp:1379:15: Dereference of null pointer
	TTFont.cpp:2817:37: The left operand of '<<' is a garbage value
	TTFont.cpp:3533:14: The right operand of '<' is a garbage value
	TTFont.cpp:3719:16: Dereference of null pointer
	TTFont.cpp:4103:14: The right operand of '<' is a garbage value
	TTFont.cpp:4241:16: Dereference of null pointer
	TTFont.cpp:5164:18: Assigned value is garbage or undefined
	TTFont.cpp:5709:8: Dereference of null pointer
	TTFont.cpp:5716:8: Dereference of null pointer
Memory error Group
	List.cpp:56:1: Potential leak of memory pointed to by 'copy'
	List.cpp:108:3: Argument to 'delete' is the address of the local variable 'curr', which is not memory allocated by 'new'
```

**Comment by simoncozens** [comment]
That's just clang. :-)

**Comment by schriftgestalt** [comment]
I know. But the warnings and issues are much more visible and and so more likely to be fixed. When I see how many warnings you get when you compline core code like freetype. It just scrolls by and nobody seems to care.

**Comment by HinTak** [comment]
Hmm, freetype does not generate that many warnings? I only know of one (about harfbuzz) that has been there for years.

The vtt code is in quite a poor state at the moment - I am not worried about warnings when there are bigger issues.

**Comment by simoncozens** [comment]
> Rather than OS specific builds, it would be better to move to a cross-platform build system. Apparently there’s a tool which can convert MSVS project files to CMakeLists and we can maybe build with ninja. I’ll give that a try on Monday.

Done in https://github.com/HinTak/VisualTrueType/pull/3

**Comment by HinTak** [comment]
On source code files' encoding, I assume that non-ascii and non-utf8 means windows 1252. However, a few still don't make sense, so I guess what they should be and try to find a decoding so it decodes to sinethung readable, and found that some non-ascii comments are in macintosh encoding. And one files have non-ascii comments of both types - some only make sense if decodes as windows 1252, some only as macintosh. This probably suggests that that file came from Apple 20+ years ago, and been worked on at Microsoft since, so have both kinds of non-ascii comments.

Details in the commit log history of mine .

**Comment by HinTak** [comment]
This can close, as we now have 3 ways of building for mac - xcode, make and cmake...
